sudo: false
language: node_js

cache: yarn

# Use latest stable yarn version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - name: "Lint"
      node_js: "10"
      script: make lint
    - name: "Build"
      node_js: "10"
      script: make build
    - name: "Test on Node.js v8.x"
      node_js: "8"
      script: make test
    - name: "Test on Node.js v10.x"
      node_js: "10"
      script: make test
